### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by ncraveia** [jancelin/rpi-docker-lizmap#2]
Bonjour,

RPi 3, Hypriot
Je viens de suivre à la lettre l'installation de Lizmap sur un rpi (https://github.com/jancelin/geo-poppy/wiki/3.-installation-des-services-base-de-donn%C3%A9es-et-websig)

J'obtiens une erreur 500 quand j'essaye d'aller sur l'adresse http://"ip local rpi"/websig/lizmap/www/admin.php

```

Error 500. A technical error has occured. Sorry for this trouble.
Application log directory is not writable
```

J'ai aussi effectué un changement de droit sur le dossier lizmap_var et lizmap_projet en faisant 
chown :www-data /home/lizmap_var -R
chown :www-data /home/lizmap_project -R
chmod 775 /home/lizmap_var -R

mais cela ne change rien, il y a toujours l'error 500

je viens de voir aussi qu'il y a une difference entre[ Rpi-docker-lizmap](https://github.com/jancelin/rpi-docker-lizmap) et le lien d'explication de [geopoppy](https://github.com/jancelin/geo-poppy/wiki/3.-installation-des-services-base-de-donn%C3%A9es-et-websig) pourquoi ?
Je signal le problème pour essayer de trouver une solution et améliorer la notice

**Comment by jancelin** [comment]
Salut,
Il faudrait tout d'abord vérifier que c'est juste un problème sur la copie du /var ou un problème sur l'image.
Lancer un conteneur sans le -v /var:
`docker run --name "lizmap_temp" -p 8081:80 -d -t -v /home/votre_dossier_qgis:/home lizmap`
et ce rendre sur http://ip:8081/websig/lizmap/www/admin.php pour paramétrer le back-office en rajoutant le dossier /home. cf doc géopoppy : 
https://cloud.githubusercontent.com/assets/6421175/11306233/e945f342-8fb0-11e5-9906-4010b9398ef1.png
Déjà si ça enregistre correctement là, c'est gagné pour la suite.

ensuite dans un ternimal rentrer dans le conteneur:
`docker exec -it lizmap_temp bash`
faire une copie du dossier en conservant les droits grâce à  -avr:
`cp -avr /var/www/websig/lizmap/var /home/lizmap_var`
sortir du conteneur pour revenir sur l’hôte:

```
exit
```

et relancer un autre conteneur avec le /var sauvegardé (afin de conserver sa config):

```
docker run --restart="always" --name "lizmap" -p 80:80 -d -t \
-v /home/votre_dossier_qgis:/home \
-v /home/votre_dossier_qgis/lizmap_var:/var/www/websig/lizmap/var \
lizmap
```

et ça doit marcher...

**Comment by ncraveia** [comment]
Bonjour,

Merci pour votre aide !

Me concernant le "votre_dossier_qgis" = Lizmap_project 

Effectivement la solution marche très bien (/home/ s'enregistre bien) et j'arrive à me connecter directement en http:// myip/websig/lizmap/www/admin.php/admin/

Le problème est maintenant de mettre un projet qgs et cfg dedans. Je viens de mettre un dossier avec un .qgs et cfg dans le dossier lizmap_project mais il n'enregistre pas lors de la configuration du répertoire( message rouge en me disant que le dossier n'existe pas) :(

Voici le chemin sur le serveur : /home/lizmap_project/qgis_intranet  -> dedans il y a le fichier qgs et fcg + dossier avec la data

J'ai essayé aussi de mettre le projet dans /home/ Mais Lizmap n'affiche pas du tout le projet ( j'ai une page vide :()

Pouvez-vous me dire comment faire car là c'est différent du serveur Debian avec Lizmap dont j'ai l'habitude :)

Encore merci c'est vraiment super comme solution !

**Comment by jancelin** [comment]
Ok, je vois.
Une chose importante à savoir entre hôte et conteneur quand on utilise le -v:
/home/lizmap_project sur l'hôte = /home dans le conteneur, c'est donc le même dossier
donc /home de l'hôte n'a rien a voir dans l'affaire car il n'est pas lié par un -v.

Dans ton cas si tu met un dossier avec tes projets dans /home/lizmap_project/qgis_intranet il faut dire dans la définition du répertoire dans le back office lizmap: /home/qgis_intranet

**Comment by ncraveia** [comment]
Bonjour,

Merci beaucoup le système marche bien ! j'ai maintenant une carte :)
Oui je suis débutant en Docker mais je découvre et je viens de comprendre là (merci :))
Par contre je viens de perdre la connexion à distance ( pas avec l'adresse ip local) du site après l’arrêt du RPI3 (débranchement du RPI3)

C'est assez bizarre de perdre la connexion internet mais pas local  après un redémarrage du RPI3  ?

Pouvez-vous nous dire comment redémarrer proprement le docker lizmap s'il vous plait.

Merci en tout cas

**Comment by jancelin** [comment]
docker ps -a :  permet de voir l'état des conteneur, il peut arriver que le conteneur lizmap ne soit plus disponible après un crach du rpi. dans ce cas là le plus simple et de tout arreter supprimer et reconstruire, c'est le principe de docker et c'est pour ça que les fichiers de conf doivent être rémanent afin de ne pas refaire la manip à chaque fois.
`docker stop lizmap && docker rm lizmap`
puis reconstruire avec

```
docker run --restart="always" --name "lizmap" -p 80:80 -d -t \
-v /home/votre_dossier_qgis:/home \
-v /home/votre_dossier_qgis/lizmap_var:/var/www/websig/lizmap/var \
lizmap
```

**Comment by ncraveia** [comment]
Bonjour, 
Je ne suis pas sur que le problème soit terminé. En effet j'ai eu des résultats (4  installations)dans la semaine ! mais le samedi j'ai voulu refaire l’installation  ( construction de l'image etc) et là votre solution ne marche plus du tout ....( j'ai une erreur 500 différente alors que je viens de refaire la même installation !!). C'est vraiment très bizarre. 

`Error 500. A technical error has occured. Sorry for this trouble.

Error in the main configuration. A plugin doesn't exist`
